POST http://localhost:8080/config
content-type: application/json

{
    "service": "sample",
    "data": {
      "key1": "value1",
      "key2": "value2"
    }
}

###

GET http://localhost:8080/config?service=sample

###

PUT http://localhost:8080/config
content-type: application/json

{
    "service": "sample",
    "data": {
      "key1": "value3",
      "key2": "value4"
    }
}

###

GET http://localhost:8080/config?service=sample

###

GET http://localhost:8080/config?service=sample&version=1

###

DELETE http://localhost:8080/config?service=sample&version=2

###

GET http://localhost:8080/config?service=sample

###

DELETE http://localhost:8080/config?service=sample

###

GET http://localhost:8080/config?service=sample

###